-- 20260930012957_seed_catalogos.sql
-- Solo catalogos y configuracion. NO se insertan becas: solo datos reales curados por humanos.

insert into public.config (clave, valor, descripcion) values
  ('dias_cierra_pronto',        '14',  'Dias antes del deadline para estado cierra_pronto. Valor provisional; se ajusta en Fase 3 UX.'),
  ('dias_verificacion_antigua', '180', 'Dias tras los cuales una verificacion se considera antigua (y una beca rolling pasa a por_confirmar). Valor provisional.')
on conflict (clave) do nothing;

insert into public.area (slug, nombre_es) values
  ('todas-las-areas',           'Todas las áreas'),
  ('ingenieria-tecnologia',     'Ingeniería y tecnología'),
  ('matematicas-computacion',   'Matemáticas e informática'),
  ('ciencias-naturales',        'Ciencias naturales'),
  ('ciencias-salud',            'Ciencias de la salud'),
  ('ciencias-sociales',         'Ciencias sociales'),
  ('humanidades',               'Humanidades'),
  ('artes-diseno',              'Artes y diseño'),
  ('negocios-economia',         'Negocios y economía'),
  ('derecho-politicas-publicas','Derecho y políticas públicas'),
  ('educacion',                 'Educación'),
  ('agricultura-medio-ambiente','Agricultura y medio ambiente'),
  ('comunicacion-periodismo',   'Comunicación y periodismo'),
  ('desarrollo-sostenible',     'Desarrollo y sostenibilidad')
on conflict (slug) do nothing;

-- ISO 3166-1 (249 entradas). Nota: Kosovo (XK) no es ISO 3166-1; agregarlo a mano si hiciera falta.
insert into public.pais (iso2, iso3, nombre_es, nombre_en) values
('AD','AND','Andorra','Andorra'),
('AE','ARE','Emiratos Árabes Unidos','United Arab Emirates'),
('AF','AFG','Afganistán','Afghanistan'),
('AG','ATG','Antigua y Barbuda','Antigua and Barbuda'),
('AI','AIA','Anguila','Anguilla'),
('AL','ALB','Albania','Albania'),
('AM','ARM','Armenia','Armenia'),
('AO','AGO','Angola','Angola'),
('AQ','ATA','Antártida','Antarctica'),
('AR','ARG','Argentina','Argentina'),
('AS','ASM','Samoa Americana','American Samoa'),
('AT','AUT','Austria','Austria'),
('AU','AUS','Australia','Australia'),
('AW','ABW','Aruba','Aruba'),
('AX','ALA','Islas Åland','Åland Islands'),
('AZ','AZE','Azerbaiyán','Azerbaijan'),
('BA','BIH','Bosnia y Herzegovina','Bosnia and Herzegovina'),
('BB','BRB','Barbados','Barbados'),
('BD','BGD','Bangladés','Bangladesh'),
('BE','BEL','Bélgica','Belgium'),
('BF','BFA','Burkina Faso','Burkina Faso'),
('BG','BGR','Bulgaria','Bulgaria'),
('BH','BHR','Baréin','Bahrain'),
('BI','BDI','Burundi','Burundi'),
('BJ','BEN','Benín','Benin'),
('BL','BLM','San Bartolomé','Saint Barthélemy'),
('BM','BMU','Bermudas','Bermuda'),
('BN','BRN','Brunéi','Brunei Darussalam'),
('BO','BOL','Bolivia','Bolivia'),
('BQ','BES','Bonaire, San Eustaquio y Saba','Bonaire, Sint Eustatius and Saba'),
('BR','BRA','Brasil','Brazil'),
('BS','BHS','Bahamas','Bahamas'),
('BT','BTN','Bután','Bhutan'),
('BV','BVT','Isla Bouvet','Bouvet Island'),
('BW','BWA','Botsuana','Botswana'),
('BY','BLR','Bielorrusia','Belarus'),
('BZ','BLZ','Belice','Belize'),
('CA','CAN','Canadá','Canada'),
('CC','CCK','Islas Cocos','Cocos (Keeling) Islands'),
('CD','COD','República Democrática del Congo','Democratic Republic of the Congo'),
('CF','CAF','República Centroafricana','Central African Republic'),
('CG','COG','Congo','Congo'),
('CH','CHE','Suiza','Switzerland'),
('CI','CIV','Costa de Marfil','Côte d''Ivoire'),
('CK','COK','Islas Cook','Cook Islands'),
('CL','CHL','Chile','Chile'),
('CM','CMR','Camerún','Cameroon'),
('CN','CHN','China','China'),
('CO','COL','Colombia','Colombia'),
('CR','CRI','Costa Rica','Costa Rica'),
('CU','CUB','Cuba','Cuba'),
('CV','CPV','Cabo Verde','Cabo Verde'),
('CW','CUW','Curazao','Curaçao'),
('CX','CXR','Isla de Navidad','Christmas Island'),
('CY','CYP','Chipre','Cyprus'),
('CZ','CZE','Chequia','Czechia'),
('DE','DEU','Alemania','Germany'),
('DJ','DJI','Yibuti','Djibouti'),
('DK','DNK','Dinamarca','Denmark'),
('DM','DMA','Dominica','Dominica'),
('DO','DOM','República Dominicana','Dominican Republic'),
('DZ','DZA','Argelia','Algeria'),
('EC','ECU','Ecuador','Ecuador'),
('EE','EST','Estonia','Estonia'),
('EG','EGY','Egipto','Egypt'),
('EH','ESH','Sahara Occidental','Western Sahara'),
('ER','ERI','Eritrea','Eritrea'),
('ES','ESP','España','Spain'),
('ET','ETH','Etiopía','Ethiopia'),
('FI','FIN','Finlandia','Finland'),
('FJ','FJI','Fiyi','Fiji'),
('FK','FLK','Islas Malvinas','Falkland Islands (Malvinas)'),
('FM','FSM','Micronesia','Micronesia (Federated States of)'),
('FO','FRO','Islas Feroe','Faroe Islands'),
('FR','FRA','Francia','France'),
('GA','GAB','Gabón','Gabon'),
('GB','GBR','Reino Unido','United Kingdom'),
('GD','GRD','Granada','Grenada'),
('GE','GEO','Georgia','Georgia'),
('GF','GUF','Guayana Francesa','French Guiana'),
('GG','GGY','Guernsey','Guernsey'),
('GH','GHA','Ghana','Ghana'),
('GI','GIB','Gibraltar','Gibraltar'),
('GL','GRL','Groenlandia','Greenland'),
('GM','GMB','Gambia','Gambia'),
('GN','GIN','Guinea','Guinea'),
('GP','GLP','Guadalupe','Guadeloupe'),
('GQ','GNQ','Guinea Ecuatorial','Equatorial Guinea'),
('GR','GRC','Grecia','Greece'),
('GS','SGS','Islas Georgia del Sur y Sandwich del Sur','South Georgia and the South Sandwich Islands'),
('GT','GTM','Guatemala','Guatemala'),
('GU','GUM','Guam','Guam'),
('GW','GNB','Guinea-Bisáu','Guinea-Bissau'),
('GY','GUY','Guyana','Guyana'),
('HK','HKG','Hong Kong','Hong Kong'),
('HM','HMD','Islas Heard y McDonald','Heard Island and McDonald Islands'),
('HN','HND','Honduras','Honduras'),
('HR','HRV','Croacia','Croatia'),
('HT','HTI','Haití','Haiti'),
('HU','HUN','Hungría','Hungary'),
('ID','IDN','Indonesia','Indonesia'),
('IE','IRL','Irlanda','Ireland'),
('IL','ISR','Israel','Israel'),
('IM','IMN','Isla de Man','Isle of Man'),
('IN','IND','India','India'),
('IO','IOT','Territorio Británico del Océano Índico','British Indian Ocean Territory'),
('IQ','IRQ','Irak','Iraq'),
('IR','IRN','Irán','Iran'),
('IS','ISL','Islandia','Iceland'),
('IT','ITA','Italia','Italy'),
('JE','JEY','Jersey','Jersey'),
('JM','JAM','Jamaica','Jamaica'),
('JO','JOR','Jordania','Jordan'),
('JP','JPN','Japón','Japan'),
('KE','KEN','Kenia','Kenya'),
('KG','KGZ','Kirguistán','Kyrgyzstan'),
('KH','KHM','Camboya','Cambodia'),
('KI','KIR','Kiribati','Kiribati'),
('KM','COM','Comoras','Comoros'),
('KN','KNA','San Cristóbal y Nieves','Saint Kitts and Nevis'),
('KP','PRK','Corea del Norte','North Korea'),
('KR','KOR','Corea del Sur','South Korea'),
('KW','KWT','Kuwait','Kuwait'),
('KY','CYM','Islas Caimán','Cayman Islands'),
('KZ','KAZ','Kazajistán','Kazakhstan'),
('LA','LAO','Laos','Laos'),
('LB','LBN','Líbano','Lebanon'),
('LC','LCA','Santa Lucía','Saint Lucia'),
('LI','LIE','Liechtenstein','Liechtenstein'),
('LK','LKA','Sri Lanka','Sri Lanka'),
('LR','LBR','Liberia','Liberia'),
('LS','LSO','Lesoto','Lesotho'),
('LT','LTU','Lituania','Lithuania'),
('LU','LUX','Luxemburgo','Luxembourg'),
('LV','LVA','Letonia','Latvia'),
('LY','LBY','Libia','Libya'),
('MA','MAR','Marruecos','Morocco'),
('MC','MCO','Mónaco','Monaco'),
('MD','MDA','Moldavia','Moldova'),
('ME','MNE','Montenegro','Montenegro'),
('MF','MAF','San Martín (parte francesa)','Saint Martin (French part)'),
('MG','MDG','Madagascar','Madagascar'),
('MH','MHL','Islas Marshall','Marshall Islands'),
('MK','MKD','Macedonia del Norte','North Macedonia'),
('ML','MLI','Mali','Mali'),
('MM','MMR','Myanmar','Myanmar'),
('MN','MNG','Mongolia','Mongolia'),
('MO','MAC','Macao','Macao'),
('MP','MNP','Islas Marianas del Norte','Northern Mariana Islands'),
('MQ','MTQ','Martinica','Martinique'),
('MR','MRT','Mauritania','Mauritania'),
('MS','MSR','Montserrat','Montserrat'),
('MT','MLT','Malta','Malta'),
('MU','MUS','Mauricio','Mauritius'),
('MV','MDV','Maldivas','Maldives'),
('MW','MWI','Malaui','Malawi'),
('MX','MEX','México','Mexico'),
('MY','MYS','Malasia','Malaysia'),
('MZ','MOZ','Mozambique','Mozambique'),
('NA','NAM','Namibia','Namibia'),
('NC','NCL','Nueva Caledonia','New Caledonia'),
('NE','NER','Níger','Niger'),
('NF','NFK','Isla Norfolk','Norfolk Island'),
('NG','NGA','Nigeria','Nigeria'),
('NI','NIC','Nicaragua','Nicaragua'),
('NL','NLD','Países Bajos','Netherlands'),
('NO','NOR','Noruega','Norway'),
('NP','NPL','Nepal','Nepal'),
('NR','NRU','Nauru','Nauru'),
('NU','NIU','Niue','Niue'),
('NZ','NZL','Nueva Zelanda','New Zealand'),
('OM','OMN','Omán','Oman'),
('PA','PAN','Panamá','Panama'),
('PE','PER','Perú','Peru'),
('PF','PYF','Polinesia Francesa','French Polynesia'),
('PG','PNG','Papúa Nueva Guinea','Papua New Guinea'),
('PH','PHL','Filipinas','Philippines'),
('PK','PAK','Pakistán','Pakistan'),
('PL','POL','Polonia','Poland'),
('PM','SPM','San Pedro y Miquelón','Saint Pierre and Miquelon'),
('PN','PCN','Islas Pitcairn','Pitcairn'),
('PR','PRI','Puerto Rico','Puerto Rico'),
('PS','PSE','Palestina','Palestine, State of'),
('PT','PRT','Portugal','Portugal'),
('PW','PLW','Palaos','Palau'),
('PY','PRY','Paraguay','Paraguay'),
('QA','QAT','Catar','Qatar'),
('RE','REU','Reunión','Réunion'),
('RO','ROU','Rumanía','Romania'),
('RS','SRB','Serbia','Serbia'),
('RU','RUS','Rusia','Russia'),
('RW','RWA','Ruanda','Rwanda'),
('SA','SAU','Arabia Saudita','Saudi Arabia'),
('SB','SLB','Islas Salomón','Solomon Islands'),
('SC','SYC','Seychelles','Seychelles'),
('SD','SDN','Sudán','Sudan'),
('SE','SWE','Suecia','Sweden'),
('SG','SGP','Singapur','Singapore'),
('SH','SHN','Santa Elena, Ascensión y Tristán de Acuña','Saint Helena, Ascension and Tristan da Cunha'),
('SI','SVN','Eslovenia','Slovenia'),
('SJ','SJM','Svalbard y Jan Mayen','Svalbard and Jan Mayen'),
('SK','SVK','Eslovaquia','Slovakia'),
('SL','SLE','Sierra Leona','Sierra Leone'),
('SM','SMR','San Marino','San Marino'),
('SN','SEN','Senegal','Senegal'),
('SO','SOM','Somalia','Somalia'),
('SR','SUR','Surinam','Suriname'),
('SS','SSD','Sudán del Sur','South Sudan'),
('ST','STP','Santo Tomé y Príncipe','Sao Tome and Principe'),
('SV','SLV','El Salvador','El Salvador'),
('SX','SXM','Sint Maarten (parte neerlandesa)','Sint Maarten (Dutch part)'),
('SY','SYR','Siria','Syria'),
('SZ','SWZ','Esuatini','Eswatini'),
('TC','TCA','Islas Turcas y Caicos','Turks and Caicos Islands'),
('TD','TCD','Chad','Chad'),
('TF','ATF','Territorios Australes Franceses','French Southern Territories'),
('TG','TGO','Togo','Togo'),
('TH','THA','Tailandia','Thailand'),
('TJ','TJK','Tayikistán','Tajikistan'),
('TK','TKL','Tokelau','Tokelau'),
('TL','TLS','Timor Oriental','Timor-Leste'),
('TM','TKM','Turkmenistán','Turkmenistan'),
('TN','TUN','Túnez','Tunisia'),
('TO','TON','Tonga','Tonga'),
('TR','TUR','Turquía','Türkiye'),
('TT','TTO','Trinidad y Tobago','Trinidad and Tobago'),
('TV','TUV','Tuvalu','Tuvalu'),
('TW','TWN','Taiwán','Taiwan'),
('TZ','TZA','Tanzania','Tanzania'),
('UA','UKR','Ucrania','Ukraine'),
('UG','UGA','Uganda','Uganda'),
('UM','UMI','Islas menores alejadas de EE. UU.','United States Minor Outlying Islands'),
('US','USA','Estados Unidos','United States'),
('UY','URY','Uruguay','Uruguay'),
('UZ','UZB','Uzbekistán','Uzbekistan'),
('VA','VAT','Ciudad del Vaticano','Holy See'),
('VC','VCT','San Vicente y las Granadinas','Saint Vincent and the Grenadines'),
('VE','VEN','Venezuela','Venezuela'),
('VG','VGB','Islas Vírgenes Británicas','British Virgin Islands'),
('VI','VIR','Islas Vírgenes de EE. UU.','U.S. Virgin Islands'),
('VN','VNM','Vietnam','Viet Nam'),
('VU','VUT','Vanuatu','Vanuatu'),
('WF','WLF','Wallis y Futuna','Wallis and Futuna'),
('WS','WSM','Samoa','Samoa'),
('YE','YEM','Yemen','Yemen'),
('YT','MYT','Mayotte','Mayotte'),
('ZA','ZAF','Sudáfrica','South Africa'),
('ZM','ZMB','Zambia','Zambia'),
('ZW','ZWE','Zimbabue','Zimbabwe')
on conflict (iso2) do nothing;

-- Ejemplo (COMENTADO) de alta manual por un curador; no ejecutar con datos inventados:
-- insert into public.institucion (nombre, tipo, pais_iso2, url) values ('<nombre real>', 'gobierno', 'XX', 'https://...');
-- insert into public.beca (slug, titulo, institucion_id, url_oficial, tipo_cobertura, cobertura_detalle, verificado_el, verificado_por, estado_revision)
--   values ('<slug>', '<titulo>', '<uuid institucion>', 'https://...', 'no_especificada', '<texto literal de la fuente>', current_date, '<curador>', 'borrador');
-- insert into public.convocatoria (beca_id, deadline_at, deadline_tz, deadline_solo_fecha, tipo_deadline, url_fuente, verificado_el)
--   values ('<uuid beca>', public.deadline_fin_del_dia('2026-12-15', 'Europe/London'), 'Europe/London', true, 'fija', 'https://...', current_date);
